apiVersion: v1
kind: ServiceAccount
metadata:
  name: bedrock-backup-serviceaccount
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: default
  name: bedrock-backup-role
rules:
- apiGroups: ["", "apps"]
  resources: ["pods", "pods/exec", "secrets", "persistentvolumeclaims", "configmaps", "services", "deployments", "serviceaccounts", "replicasets", "cronjobs" ]
  verbs: ["get", "list", "watch", "create", "update", "patch", "delete", "exec"]
- apiGroups: [""]
  resources: ["pods/log"]
  verbs: ["get", "list", "watch"]
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: bedrock-backup-rolebinding
subjects:
- kind: ServiceAccount
  name: bedrock-backup-serviceaccount
roleRef:
  kind: Role
  name: bedrock-backup-role
  apiGroup: rbac.authorization.k8s.io