apiVersion: apps/v1
kind: Deployment
metadata:
  name: bedrock-map-sever
  labels:
    app: bedrock-map-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: bedrock-map-server
  template:
    metadata:
      labels:
        app: bedrock-map-server
    spec:
      containers:
        - name: bedrock-map-server
          image: nginx
          ports:
            - name: http
              containerPort: 80
              protocol: TCP
          volumeMounts:
          - name: datadir
            mountPath: /usr/share/nginx/html
      volumes:
      - name: datadir
        persistentVolumeClaim:
          claimName: bedrock-backup
---
apiVersion: v1
kind: Service
metadata:
  name: bedrock-map-server
spec:
  selector:
    app: bedrock-map-server
  type: ClusterIP
  ports:
    - port: 80
      targetPort: 80
      protocol: TCP
      name: http
---
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: bedrock-map-server
  labels:
    app: bedrock-map-server
  annotations:
    kubernetes.io/ingress.class: nginx
    cert-manager.io/cluster-issuer: letsencrypt
spec:
  tls:
    - hosts:
        - minecraft-map.cloudynerd.com
      secretName: bedrock-map-server-tls
  rules:
    - host: minecraft-map.cloudynerd.com
      http:
        paths:
          - path: /
            backend:
              serviceName: bedrock-map-server
              servicePort: 80
