apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: azurefile-retain
parameters:
  skuName: Standard_LRS
provisioner: kubernetes.io/azure-file
reclaimPolicy: Retain
volumeBindingMode: Immediate