apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "minecraft-bedrock.fullname" . }}
  labels:
    {{- include "minecraft-bedrock.labels" . | nindent 4 }}
spec:
  replicas: 1
  selector:
    matchLabels:
      {{- include "minecraft-bedrock.selectorLabels" . | nindent 6 }}
  template:
    metadata:
    {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
    {{- end }}
      labels:
        {{- include "minecraft-bedrock.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "minecraft-bedrock.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          tty: true
          stdin: true
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: minecraft-udp
              containerPort: 19132
              protocol: UDP
          env:
            - name: GAMEMODE
              value: {{ .Values.minecraftServer.gameMode | quote }}
            - name: DIFFICULTY
              value: {{ .Values.minecraftServer.difficulty | quote }}
            - name: WHITE_LIST
              value: {{ .Values.minecraftServer.whitelist | quote }}
            - name: MAX_PLAYERS
              value: {{ .Values.minecraftServer.maxPlayers | quote }}
            - name: ONLINE_MODE
              value: {{ .Values.minecraftServer.onlineMode | quote }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          volumeMounts:
          - name: datadir
            mountPath: /data
      volumes:
      - name: datadir
      {{- if .Values.persistence.dataDir.enabled }}
        persistentVolumeClaim:
          claimName: {{ template "minecraft-bedrock.fullname" . }}-datadir
      {{- else }}
        emptyDir: {}
      {{- end }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}