apiVersion: v1
kind: Service
metadata:
  name: {{ include "minecraft-bedrock.fullname" . }}
  labels:
    {{- include "minecraft-bedrock.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 19132
      protocol: UDP
      name: minecraft-udp
  selector:
    {{- include "minecraft-bedrock.selectorLabels" . | nindent 4 }}
